split: train

background_dir:
  - "/Users/selbouch/Desktop/Chapter6/data_npz/snippetsBF_4768x256_BA"
  - "/Users/selbouch/Desktop/Chapter6/data_npz/snippetsHF_4768x256_BA"

test_frac: 0.2
split_seed: 21

n_frb: 5
n_background: 5

output_file: "train_data_chapter6.hdf5"
target_shape: [256, 256]

parameters_train:
  dm:
    distribution: lognormal
    mu: 6.
    sigma: 1.
    log: true
  snr:
    distribution: loguniform
    low: 5
    high: 100
    log: true
  width_s:
    distribution: lognormal
    mu: -6.9
    sigma: 1
    log: true
  scat_s:
    distribution: loguniform
    mu: -4.6
    sigma: 1
    log: true
  spec_id:
    distribution: uniform
    low: -4
    high: 4
    log: false